---
api:
  dashboard: true
providers:
  file:
    filename: /etc/traefik/dynamic.yml
  docker:
    network: local
    defaultRule: "Host(`{{ .Name }}.test`)"
    exposedByDefault: false
entryPoints:
  https:
    address: ":443"
log:
  level: info
global:
  checkNewVersion: true
  sendAnonymousUsage: false