version: "3.5"
services:
  traefik:
    container_name: traefik
    image: traefik:latest
    ports:
      - "80:80"     # The HTTP port
      - "443:443"   # The HTTPS port
    volumes:
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml
      - ./traefik/dynamic.yml:/etc/traefik/dynamic.yml
      - ./ssl/certs:/etc/ssl/certs
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.tls=true
      - traefik.http.routers.traefik.rule=Host(`traefik.local.test`)
      - traefik.http.routers.traefik.service=api@internal
    restart: always

  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    command: --admin-password '$$2y$$05$$bvgK33Xc82dhIzDP34MhPOlGTwCitUL96ET11eSt1Az6aDXCTzbfe'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/portainer:/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.portainer.tls=true
      - traefik.http.routers.portainer.rule=Host(`portainer.local.test`)
      - traefik.http.services.portainer.loadbalancer.server.port=9000
    restart: always
  mailhog:
    container_name: mailhog
    hostname: mailhog.magento2.docker
    image: mailhog/mailhog
    restart: always
    ports:
      - "1025:1025"
    labels:
      - traefik.enable=true
      - traefik.http.routers.mailhog.tls=true
      - traefik.http.routers.mailhog.rule=Host(`mailhog.local.test`)
      - traefik.http.services.mailhog.loadbalancer.server.port=8025
  db:
    container_name: db
    image: 'mariadb:10.4'
    ports:
      - '3306:3306'
    command: >
      bash -c "
      chmod 644 /etc/mysql/conf.d/*.cnf
      && docker-entrypoint.sh mysqld
      "
    volumes:
      - ~/mysql:/var/lib/mysql
      - ./mysql/custom-config.cnf:/etc/mysql/conf.d/custom-config.cnf
    restart: unless-stopped
    hostname: db.magento2.docker
    environment:
      - MYSQL_ROOT_PASSWORD=magento2
      - MYSQL_DATABASE=mag22
      - MYSQL_USER=magento2
      - MYSQL_PASSWORD=magento2
volumes:
  portainer:
  sshd_keys:

networks:
  default:
    name: local
