version: "3.5"
services:
  traefik:
    container_name: traefik
    image: traefik:latest
    ports:
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.tls=true
      - traefik.http.routers.traefik.rule=Host(`traefik.local.test`)
      - traefik.http.routers.traefik.service=api@internal
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.network=local"
      - "--providers.docker.defaultRule=Host(`{{ .Name }}.local.test`)"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.https=true"
      - "--entryPoints.https.address=:443"
      - "--log.level=INFO"
      - "--global.checkNewVersion=true"
      - "--global.sendAnonymousUsage=false"
    restart: always

  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    command: --admin-password '$$2y$$05$$bvgK33Xc82dhIzDP34MhPOlGTwCitUL96ET11eSt1Az6aDXCTzbfe'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/portainer:/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.portainer.tls=true
      - traefik.http.routers.portainer.rule=Host(`portainer.local.test`)
      - traefik.http.services.portainer.loadbalancer.server.port=9000
    restart: always

  mailhog:
    container_name: mailhog
    hostname: mailhog.magento2.docker
    image: mailhog/mailhog
    restart: always
    ports:
      - "1025:1025"
    labels:
      - traefik.enable=true
      - traefik.http.routers.mailhog.tls=true
      - traefik.http.routers.mailhog.rule=Host(`mailhog.local.test`)
      - traefik.http.services.mailhog.loadbalancer.server.port=8025

  db:
    container_name: db
    image: 'mariadb:10.4'
    ports:
      - '3306:3306'
    command: >
      bash -c "
      chmod 644 /etc/mysql/conf.d/*.cnf
      && docker-entrypoint.sh mysqld
      "
    volumes:
      - ~/mysql:/var/lib/mysql
      - ./mysql/custom-config.cnf:/etc/mysql/conf.d/custom-config.cnf
    restart: unless-stopped
    hostname: db.magento2.docker
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=magento
      - MYSQL_USER=magento
      - MYSQL_PASSWORD=magento

  adminer:
    container_name: adminer
    hostname: adminer.magento2.docker
    image: adminer
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: db
    labels:
      - traefik.enable=true
      - traefik.http.routers.adminer.tls=true
      - traefik.http.routers.adminer.rule=Host(`adminer.local.test`)
      - traefik.http.services.adminer.loadbalancer.server.port=8080

  ssh-agent:
    image: 'docksal/ssh-agent'
    volumes:
      - ~/.ssh:/root/.ssh:ro
      - ssh-socket:/.ssh-agent
    restart: always

volumes:
  ssh-socket:
    name: ssh-socket

networks:
  default:
    name: local
