version: '3.8'

services:
  fpm:
    image: 'sashas777/magento-php:7.4-fpm'
    container_name: mag22-fpm
    hostname: fpm.magento2.docker
    restart: unless-stopped
    volumes:
      - ./src:/var/www/magento:rw
  web:
    image: 'sashas777/magento-nginx:latest'
    container_name: mag22-web
    depends_on:
      - fpm
    environment:
      - FPM_HOST=mag22-fpm
    restart: unless-stopped
    volumes:
      - ./src:/var/www/magento:rw
    labels:
      - traefik.enable=false
      - traefik.http.routers.mag22-web.tls=false
      - traefik.http.routers.mag22-web.rule=Host(`mag22.local.test`)
      - traefik.http.services.mag22-web.loadbalancer.server.port=8080
  cli:
    image: 'sashas777/magento-php:7.4-cli'
    container_name: mag22-cli
    hostname: cli.magento2.docker
    restart: unless-stopped
    command: run-cron
    cap_add:
      - NET_ADMIN
    depends_on:
      - elasticsearch
    volumes:
      - ~/.cache/composer:/root/.cache/composer:rw
      - ./src:/var/www/magento:rw
  elasticsearch:
    image: 'sashas777/magento-elasticsearch:7.9.3'
    container_name: mag22-elasticsearch
    hostname: elasticsearch.mag22.local.test
    restart: unless-stopped
    environment:
      ES_NETWORK_HOST: 'localhost'
      ES_JAVA_OPTS: '-Xms1024m -Xmx1024m'
  rabbitmq:
    image: rabbitmq:3.8-management
    hostname: rabbitmq.mag22.local.test
    container_name: mag22-rabbitmq
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.mag22-rabbitmq.tls=true
      - traefik.http.routers.mag22-rabbitmq.rule=Host(`rabbitmq.mag22.local.test`)
      - traefik.http.services.mag22-rabbitmq.loadbalancer.server.port=15672
    volumes:
      - ./dev/rabbitmq:/var/lib/rabbitmq
  redis:
    image: 'sashas777/magento-redis:5.0'
    container_name: mag22-redis
    hostname: redis.mag22.local.test
    restart: unless-stopped
    volumes:
      - ./dev/redis:/data
  varnish:
    image: 'sashas777/magento-varnish:7.0'
    container_name: mag22-varnish
    hostname: varnish.mag22.local.test
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.mag22-varnish.tls=true
      - traefik.http.routers.mag22-varnish.priority=1
      - traefik.http.routers.mag22-varnish.rule=Host(`varnish.mag22.local.test`)
      - traefik.http.services.mag22-varnish.loadbalancer.server.port=80

volumes:
  ssh-socket:
    external:
      name: ssh-socket

networks:
  default:
    external:
      name: local
